import javax.swing.*;//provides classes for building GUI(graphic user interface)
import java.awt.*;//provides classes for managing GUI components
import java.awt.event.*;//provides classes and interfaces for handling events generated by user interactions
import java.sql.*;//provides classes and interfaces for accessing and processing data stored in a database


public class LangApp {
    public static void main(String[] args) {

        //frontpage/login
        //language tree
        //lang lists (families)

        //phoenic alphabet

        //rules
        //vocab
        //practice (stories/conversation)
        //progress

        //report problems
        //loading page with fun language facts

        //vocab database
        //letters database
        // sounds database

        //new keyboard

        //spokenlangs
            //romance
                //spanish
                //french
            //germanic
                //english
                //german
            //slavic
            //whatever the asian language families are called
                //chinese
                //japanese

        //endangeredlangs


        //unusuallangs
            //whistlinglangs(silbogomero)

        //ancientlangs
            //ancient egyptian
            //ancient norse

        //conlangs
            //esperanto
            //tokipona


        //sources
        //donate?;)



    }
}
